In [5]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("budget.db")

In [6]:
query = """
SELECT *
FROM budgets;
"""

pd.read_sql_query(query, conn)

   budget_id  user_id  category_id    month  budget_amount
0          1        1            1  2026-08          150.0
1          2        1            2  2026-08          250.0
2          3        1            3  2026-08          140.0
3          4        1            4  2026-08          200.0
4          5        1            5  2026-08          100.0
5          6        1            6  2026-08           75.0
6          7        1            7  2026-08          120.0
7          8        1            8  2026-08           90.0
8          9        1            9  2026-08          700.0

In [7]:
query = """
SELECT *
FROM categories;
"""

pd.read_sql_query(query, conn)

    category_id   category_name
0             1          Dining
1             2       Groceries
2             3             Gas
3             4        Shopping
4             5   Entertainment
5             6   Subscriptions
6             7  Transportation
7             8   Personal Care
8             9           Bills
9            10          Income
10           11        Transfer

In [8]:
query = """
SELECT categories.category_name, budgets.budget_amount
FROM budgets
JOIN categories
ON budgets.category_id = categories.category_id;
"""

budget_df = pd.read_sql_query(query, conn)

budget_df

    category_name  budget_amount
0          Dining          150.0
1       Groceries          250.0
2             Gas          140.0
3        Shopping          200.0
4   Entertainment          100.0
5   Subscriptions           75.0
6  Transportation          120.0
7   Personal Care           90.0
8           Bills          700.0

In [9]:
query = """
SELECT category_id, SUM(amount) AS total_spent
FROM transactions
WHERE transaction_type = 'Purchase'
GROUP BY category_id;
"""

spending_df = pd.read_sql_query(query, conn)

spending_df

   category_id  total_spent
0            1       131.41
1            2       403.37
2            3       258.86
3            4       206.64
4            5       179.70
5            6        22.79
6            7       169.24
7            8       256.29
8            9      2613.34

In [10]:
query = """
SELECT 
    categories.category_name,
    SUM(transactions.amount) AS total_spent
FROM transactions
JOIN categories
    ON transactions.category_id = categories.category_id
WHERE transactions.transaction_type = 'Purchase'
GROUP BY categories.category_name;
"""

spending_df = pd.read_sql_query(query, conn)

spending_df

    category_name  total_spent
0           Bills      2613.34
1          Dining       131.41
2   Entertainment       179.70
3             Gas       258.86
4       Groceries       403.37
5   Personal Care       256.29
6        Shopping       206.64
7   Subscriptions        22.79
8  Transportation       169.24